In [16]:
import gym
import numpy as np
from tqdm.notebook import tnrange
import random

In [9]:
env = gym.make("FrozenLake-v0")
#env = gym.make("FrozenLake-v0", is_slippery=False)

In [10]:
action_space_size = env.action_space.n  #rows of q table
state_space_size =  env.observation_space.n #cols of q table

In [11]:
#initiate q table with zeros
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
num_episodes = 9500
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.001

In [17]:
rewards_all_episodes=[]
for episode in tnrange(num_episodes):
    
    state = env.reset()
    done=False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_switch = random.uniform(0,1)
        
        if exploration_switch > exploration_rate:
            #exploit
            action = np.argmax(q_table[state,:])
        else:
            #explore = sample an action randomly
            action = env.action_space.sample()
            
        #action has been chosen, now step
        new_state, reward, done, info = env.step(action)
        
        #update q table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        #update state
        state = new_state
        
        #update rewards
        rewards_current_episode += reward
        
        if done==True:
            break
    
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    