In [8]:
import gym
import numpy as np

In [9]:
env = gym.make("FrozenLake-v0")
#env = gym.make("FrozenLake-v0", is_slippery=False)

In [10]:
action_space_size = env.action_space.n  #rows of q table
state_space_size =  env.observation_space.n #cols of q table

In [11]:
#initiate q table with zeros
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
